"""Initial database schema

Revision ID: 001
Revises: 
Create Date: 2024-12-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create UUID extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # Create resumes table
    op.create_table('resumes',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('uuid_generate_v4()')),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('text_content', sa.Text(), nullable=False),
        sa.Column('s3_url', sa.String(length=500), nullable=False),
        sa.Column('job_description', sa.Text(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_resumes_uploaded_at'), 'resumes', ['uploaded_at'], unique=False)
    
    # Create feedback_sessions table
    op.create_table('feedback_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('uuid_generate_v4()')),
        sa.Column('resume_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_feedback_sessions_resume_id'), 'feedback_sessions', ['resume_id'], unique=False)
    op.create_index(op.f('idx_feedback_sessions_status'), 'feedback_sessions', ['status'], unique=False)
    
    # Create agent_responses table
    op.create_table('agent_responses',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('uuid_generate_v4()')),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('agent_name', sa.String(length=50), nullable=False),
        sa.Column('response_text', sa.Text(), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('feedback_rating', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['feedback_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_agent_responses_session_id'), 'agent_responses', ['session_id'], unique=False)
    op.create_index(op.f('idx_agent_responses_agent_name'), 'agent_responses', ['agent_name'], unique=False)
    op.create_index(op.f('idx_agent_responses_created_at'), 'agent_responses', ['created_at'], unique=False)
    
    # Create aggregated_learnings table
    op.create_table('aggregated_learnings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('uuid_generate_v4()')),
        sa.Column('pattern_type', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('frequency', sa.Integer(), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('agent_name', sa.String(length=50), nullable=False),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_aggregated_learnings_agent_name'), 'aggregated_learnings', ['agent_name'], unique=False)
    op.create_index(op.f('idx_aggregated_learnings_pattern_type'), 'aggregated_learnings', ['pattern_type'], unique=False)
    op.create_index(op.f('idx_aggregated_learnings_confidence_score'), 'aggregated_learnings', ['confidence_score'], unique=False)
    
    # Insert sample aggregated learnings for testing
    op.execute("""
        INSERT INTO aggregated_learnings (id, pattern_type, description, frequency, confidence_score, agent_name, last_updated)
        VALUES 
            (uuid_generate_v4(), 'positive_feedback', 'Users appreciate specific examples and quantified achievements', 5, 0.8, 'critic', NOW()),
            (uuid_generate_v4(), 'negative_feedback', 'Generic buzzwords without context are not helpful', 3, 0.7, 'critic', NOW()),
            (uuid_generate_v4(), 'positive_feedback', 'Highlighting transferable skills resonates well with users', 4, 0.75, 'advocate', NOW()),
            (uuid_generate_v4(), 'skill_gap', 'Technical certifications are often missing from developer resumes', 6, 0.85, 'realist', NOW())
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_aggregated_learnings_confidence_score'), table_name='aggregated_learnings')
    op.drop_index(op.f('idx_aggregated_learnings_pattern_type'), table_name='aggregated_learnings')
    op.drop_index(op.f('idx_aggregated_learnings_agent_name'), table_name='aggregated_learnings')
    op.drop_table('aggregated_learnings')
    
    op.drop_index(op.f('idx_agent_responses_created_at'), table_name='agent_responses')
    op.drop_index(op.f('idx_agent_responses_agent_name'), table_name='agent_responses')
    op.drop_index(op.f('idx_agent_responses_session_id'), table_name='agent_responses')
    op.drop_table('agent_responses')
    
    op.drop_index(op.f('idx_feedback_sessions_status'), table_name='feedback_sessions')
    op.drop_index(op.f('idx_feedback_sessions_resume_id'), table_name='feedback_sessions')
    op.drop_table('feedback_sessions')
    
    op.drop_index(op.f('idx_resumes_uploaded_at'), table_name='resumes')
    op.drop_table('resumes')
    
    # Drop UUID extension (be careful in production)
    # op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
    # ### end Alembic commands ###