"""add_foreign_key_constraints

Revision ID: 002_add_foreign_keys
Revises: 001_initial_schema
Create Date: 2025-12-09 13:18:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_foreign_keys'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add foreign key constraint for feedback_sessions.resume_id
    op.create_foreign_key(
        'fk_feedback_sessions_resume_id',
        'feedback_sessions', 
        'resumes',
        ['resume_id'], 
        ['id'],
        ondelete='CASCADE'
    )
    
    # Add foreign key constraint for agent_responses.session_id  
    op.create_foreign_key(
        'fk_agent_responses_session_id',
        'agent_responses',
        'feedback_sessions', 
        ['session_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints
    op.drop_constraint('fk_agent_responses_session_id', 'agent_responses', type_='foreignkey')
    op.drop_constraint('fk_feedback_sessions_resume_id', 'feedback_sessions', type_='foreignkey')
    
    # ### end Alembic commands ###