"""fix_column_mismatches

Revision ID: 717171247f96
Revises: 002_add_foreign_keys
Create Date: 2025-12-09 16:19:59.058618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '717171247f96'
down_revision = '002_add_foreign_keys'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_responses', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agent_responses', sa.Column('thumbs_up', sa.Boolean(), nullable=True))
    op.add_column('agent_responses', sa.Column('feedback_text', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_agent_responses_agent_name'), table_name='agent_responses')
    op.drop_index(op.f('idx_agent_responses_created_at'), table_name='agent_responses')
    op.drop_index(op.f('idx_agent_responses_session_id'), table_name='agent_responses')
    op.create_index(op.f('ix_agent_responses_session_id'), 'agent_responses', ['session_id'], unique=False)
    op.drop_constraint(op.f('agent_responses_session_id_fkey'), 'agent_responses', type_='foreignkey')
    op.create_foreign_key(None, 'agent_responses', 'feedback_sessions', ['session_id'], ['id'])
    op.drop_column('agent_responses', 'feedback_rating')
    op.drop_column('agent_responses', 'confidence_score')
    op.drop_index(op.f('idx_aggregated_learnings_agent_name'), table_name='aggregated_learnings')
    op.drop_index(op.f('idx_aggregated_learnings_confidence_score'), table_name='aggregated_learnings')
    op.drop_index(op.f('idx_aggregated_learnings_pattern_type'), table_name='aggregated_learnings')
    op.add_column('feedback_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_feedback_sessions_resume_id'), table_name='feedback_sessions')
    op.drop_index(op.f('idx_feedback_sessions_status'), table_name='feedback_sessions')
    op.create_index(op.f('ix_feedback_sessions_resume_id'), 'feedback_sessions', ['resume_id'], unique=False)
    op.drop_constraint(op.f('fk_feedback_sessions_resume_id'), 'feedback_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'feedback_sessions', 'resumes', ['resume_id'], ['id'])
    op.drop_column('feedback_sessions', 'started_at')
    op.drop_index(op.f('idx_resumes_uploaded_at'), table_name='resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_resumes_uploaded_at'), 'resumes', ['uploaded_at'], unique=False)
    op.add_column('feedback_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feedback_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_feedback_sessions_resume_id'), 'feedback_sessions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_feedback_sessions_resume_id'), table_name='feedback_sessions')
    op.create_index(op.f('idx_feedback_sessions_status'), 'feedback_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_feedback_sessions_resume_id'), 'feedback_sessions', ['resume_id'], unique=False)
    op.drop_column('feedback_sessions', 'created_at')
    op.create_index(op.f('idx_aggregated_learnings_pattern_type'), 'aggregated_learnings', ['pattern_type'], unique=False)
    op.create_index(op.f('idx_aggregated_learnings_confidence_score'), 'aggregated_learnings', ['confidence_score'], unique=False)
    op.create_index(op.f('idx_aggregated_learnings_agent_name'), 'aggregated_learnings', ['agent_name'], unique=False)
    op.add_column('agent_responses', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('agent_responses', sa.Column('feedback_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_responses', type_='foreignkey')
    op.create_foreign_key(op.f('agent_responses_session_id_fkey'), 'agent_responses', 'feedback_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_responses_session_id'), table_name='agent_responses')
    op.create_index(op.f('idx_agent_responses_session_id'), 'agent_responses', ['session_id'], unique=False)
    op.create_index(op.f('idx_agent_responses_created_at'), 'agent_responses', ['created_at'], unique=False)
    op.create_index(op.f('idx_agent_responses_agent_name'), 'agent_responses', ['agent_name'], unique=False)
    op.drop_column('agent_responses', 'feedback_text')
    op.drop_column('agent_responses', 'thumbs_up')
    op.drop_column('agent_responses', 'order')
    # ### end Alembic commands ###